# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-30 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0008_auto_20170112_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_request',
            field=models.ImageField(default=None, upload_to='request'),
            preserve_default=False,
        ),
    ]
