# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-30 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0009_profile_last_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_request',
            field=models.ImageField(blank=True, upload_to='request'),
        ),
    ]
